# Generated by Django 4.1.2 on 2023-02-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.TextField(default='')),
                ('name', models.TextField(default='anon')),
                ('country', models.TextField(default='-')),
                ('phone', models.IntegerField(default='-')),
                ('dob', models.DateField(default='-')),
                ('profilepic', models.ImageField(default='d.png', upload_to='')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
