# Generated by Django 4.1.2 on 2023-02-19 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bio_profilepic_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.TextField()),
                ('f', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='t',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='newpost',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
