# Generated by Django 4.1.2 on 2023-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_follow_post_t_alter_post_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='s',
            field=models.TextField(default='admin'),
        ),
    ]
