# Generated by Django 4.1.2 on 2023-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='un',
            field=models.TextField(default='xxxxxxxxxxxxxxxxxxx'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='country',
            field=models.TextField(default='wonderland'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
